// Mock data based on real BAFI export for אבי אנצ׳יו

export const mockCustomerDetail = {
  id: "1",
  firstName: "אבי",
  lastName: "אנצ׳יו",
  israeliId: "022268148",
  address: "משעול פלג 8, ראשון לציון",
  assignedManager: "רפי בכר",
  lastImportDate: "2026-04-05",
  importFileCount: 1,
  profileCompleteness: 2 as const,

  familyMembers: [] as { name: string; israeliId: string; source: string }[],

  // Insurance map — what categories exist
  insuranceMap: {
    PROPERTY: {
      exists: true,
      policyCount: 13,
      totalAnnualPremium: 20927,
      insurers: ["שומרה", "איילון", "כלל"],
      nearestExpiry: "2026-05-31",
      dataFreshness: "2026-04-05",
    },
    HEALTH: {
      exists: true,
      policyCount: 1,
      totalMonthlyPremium: 0,
      insurers: ["מנורה"],
      nearestExpiry: null,
      dataFreshness: "2026-01-31",
    },
    SAVINGS: {
      exists: true,
      policyCount: 1,
      totalAccumulated: 1071548,
      insurers: ["כלל"],
      dataFreshness: "2025-12-31",
    },
    LIFE: { exists: false, dataFreshness: null },
    PENSION: { exists: false, dataFreshness: null },
    RISK: { exists: false, dataFreshness: null },
    PROVIDENT: { exists: false, dataFreshness: null },
  },

  policies: [
    {
      id: "p1",
      policyNumber: "730346831126",
      insurer: "שומרה",
      category: "PROPERTY",
      subType: "רכב — מקיף",
      status: "ACTIVE",
      startDate: "2026-01-01",
      endDate: "2026-12-31",
      premiumAnnual: 9550,
      vehicleYear: 2023,
      vehiclePlate: "27969303",
      vehicleModel: "פורד אקספלורר",
      dataFreshness: "2026-04-05",
    },
    {
      id: "p2",
      policyNumber: "730346831126",
      insurer: "שומרה",
      category: "PROPERTY",
      subType: "רכב — חובה",
      status: "ACTIVE",
      startDate: "2026-01-01",
      endDate: "2026-12-31",
      premiumAnnual: 1522,
      vehicleYear: 2023,
      vehiclePlate: "27969303",
      vehicleModel: "פורד אקספלורר",
      dataFreshness: "2026-04-05",
    },
    {
      id: "p3",
      policyNumber: "33880602926",
      insurer: "איילון",
      category: "PROPERTY",
      subType: "דירה",
      status: "ACTIVE",
      startDate: "2026-01-01",
      endDate: "2026-12-31",
      premiumAnnual: 490,
      dataFreshness: "2026-04-05",
    },
    {
      id: "p4",
      policyNumber: "33888014925",
      insurer: "איילון",
      category: "PROPERTY",
      subType: "דירה",
      status: "ACTIVE",
      startDate: "2025-06-01",
      endDate: "2026-05-31",
      premiumAnnual: 1444,
      dataFreshness: "2026-04-05",
    },
    {
      id: "p5",
      policyNumber: "4662350",
      insurer: "כלל",
      category: "SAVINGS",
      subType: "פוליסת חיסכון טהור",
      status: "ACTIVE",
      startDate: "2025-06-01",
      endDate: null,
      premiumMonthly: 0,
      accumulatedSavings: 1071548,
      dataFreshness: "2025-12-31",
      investmentTracks: [
        { name: "מניות סחיר", amount: 236697, ytdReturn: 0 },
        { name: "עוקב מדדים-גמיש", amount: 405289, ytdReturn: 0.11 },
        { name: "כללי", amount: 429562, ytdReturn: 16.35 },
      ],
      feeOnAccumulationPct: 0.69,
      feeOnPremiumPct: null,
    },
    {
      id: "p6",
      policyNumber: "371110883",
      insurer: "מנורה",
      category: "HEALTH",
      subType: "חיסכון והשקעה TOP FINAN",
      status: "ACTIVE",
      startDate: "2025-06-01",
      endDate: null,
      premiumMonthly: 0,
      dataFreshness: "2026-01-31",
    },
  ],

  insights: [
    {
      id: "i1",
      category: "NO_HEALTH" as const,
      title: "לא זוהה כיסוי בריאות פעיל בנתונים שנקלטו",
      summary:
        "ללקוח פוליסה אחת בקטגוריית בריאות (מנורה) אך היא מסווגת כחיסכון והשקעה ולא ככיסוי בריאותי. לא זוהה כיסוי רפואי פעיל.",
      whyNow: "ממצא מיבוא אחרון — 05/04/2026",
      urgencyLevel: 1 as const,
      generatedBy: "DETERMINISTIC",
    },
    {
      id: "i2",
      category: "SINGLE_CATEGORY" as const,
      title: "ריכוז גבוה בביטוח רכוש",
      summary:
        "רוב הפרמיה השנתית (₪20,927) מרוכזת בביטוח רכוש. אין פנסיה, ביטוח חיים או סיכון.",
      whyNow: "ממצא מיבוא אחרון — 05/04/2026",
      urgencyLevel: 1 as const,
      generatedBy: "DETERMINISTIC",
    },
    {
      id: "i3",
      category: "HIGH_SAVINGS_LOW_PROTECTION" as const,
      title: "חיסכון גבוה ללא הגנה מתאימה",
      summary:
        "ללקוח חיסכון מצטבר של ₪1,071,548 בכלל, אך לא זוהה ביטוח חיים, סיכון, או פנסיה בנתונים שנקלטו.",
      whyNow: "ממצא מיבוא אחרון — 05/04/2026",
      urgencyLevel: 2 as const,
      generatedBy: "DETERMINISTIC",
    },
  ],

  recommendations: [
    {
      id: "r1",
      type: "COVERAGE_GAP_REVIEW",
      title: "סקירת כיסוי חיים / סיכון",
      shortExplanation:
        "ללקוח חיסכון של מעל מיליון ש״ח אך לא זוהה ביטוח חיים או סיכון בנתונים שנקלטו. מומלץ לבצע סקירה.",
      whyNow: "חיסכון מצטבר ₪1,071,548 ללא הגנה מזוהה",
      strengthLevel: 2 as const,
      urgencyLevel: 2 as const,
      status: "PENDING",
    },
    {
      id: "r2",
      type: "COVERAGE_GAP_REVIEW",
      title: "בדיקת כיסוי בריאות",
      shortExplanation:
        "הפוליסה הרשומה בקטגוריית בריאות היא חיסכון/השקעה ולא כיסוי רפואי. לא זוהה כיסוי בריאות פעיל.",
      whyNow: "לא זוהה כיסוי בריאות פעיל בנתונים שנקלטו",
      strengthLevel: 1 as const,
      urgencyLevel: 1 as const,
      status: "PENDING",
    },
  ],

  timeline: [
    {
      id: "t1",
      date: "2026-04-05",
      type: "import",
      description: "יובא קובץ BAFI — לקוח - אבי אנצ׳יו.htm",
    },
    {
      id: "t2",
      date: "2026-04-05",
      type: "insight",
      description: "זוהו 3 תובנות חדשות",
    },
    {
      id: "t3",
      date: "2026-04-05",
      type: "recommendation",
      description: "נוצרו 2 המלצות חדשות",
    },
  ],
};
