import { prisma } from "@/lib/db";

/**
 * Rafi's original 13 tips — converted to OfficeRule records with structured triggerConditions.
 */
export const RAFI_RULES = [
  {
    title: "רכב חדש — חלקים מקוריים",
    body: "יש לך מכונית חדשה עד שנתיים על הכביש? בגלל מערכות הבטיחות ברכב, תבקש מסוכן הביטוח שלך שמשות מקוריות, פנסים ומראות מקוריים.",
    category: "כיסוי",
    triggerCondition: "policy_category = PROPERTY AND policy_subtype = רכב AND vehicle_age <= 2",
    triggerHint: "רכב עד גיל 2",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: "משכנתאות מחברות ביטוח",
    body: "חברות הביטוח נכנסו היום לעולמות המשכנתאות: משכנתא הפוכה מגיל 55, משכנתא ל-40 שנה, משכנתא לנכס להשקעה, הלוואה לכל מטרה.",
    category: "כללי",
    triggerCondition: "age >= 30 AND age <= 65 AND policy_category = PROPERTY",
    triggerHint: "בעל נכס",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: "בדיקת ריבית משכנתא",
    body: "לא בדקת את הריביות במשכנתא שלך בחמש השנים האחרונות? עצור. קח ייעוץ משכנתאות דיגיטלי וחינם.",
    category: "חיסכון",
    triggerCondition: "policy_subtype = משכנתא AND policy_age_years > 5",
    triggerHint: "משכנתא מעל 5 שנים",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: 'ביטוח נסיעות לחו"ל',
    body: 'אל תחכו עם ביטוח נסיעות לחו"ל לרגע האחרון לפני הטיסה. עשו את הביטוח עם רכישת הכרטיסים ותרוויחו כיסויים נוספים.',
    category: "כיסוי",
    triggerCondition: "policy_count >= 2 AND travel_season",
    triggerHint: "עונת טיסות",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: "מחיר ביטוח חיים",
    body: "יש לך ביטוח חיים שלא בדקת את המחיר שלו בשלוש השנים האחרונות? ככל הנראב אתה משלם יקר. בדוק ותחסוך.",
    category: "חיסכון",
    triggerCondition: "policy_category = LIFE AND policy_age_years > 3",
    triggerHint: "ביטוח חיים מעל 3 שנים",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: "נספח תרופות בביטוח רפואי",
    body: "יש לך ביטוח רפואי ישן וטוב? מצוין. שים לב שנספח התרופות שלך מעודכן לנספח החדש – ישנם טכנולוגיות רבות וחדשות.",
    category: "כיסוי",
    triggerCondition: "policy_category = HEALTH AND policy_age_years > 3",
    triggerHint: "ביטוח בריאות ותיק",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: "תאונה — מוסכי הסדר בלבד",
    body: "קרתה לכם תאונה? הינכם חייבים להיכנס רק למוסכי הסדר. אחרת, חברות הביטוח עשויות לקזז כ-30% מהתביעה (באישור המפקח על הביטוח).",
    category: "שירות",
    triggerCondition: "policy_category = PROPERTY AND policy_subtype = רכב",
    triggerHint: "ביטוח רכב",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: "דירה מושכרת",
    body: "יש לכם דירה מושכרת? עדכן את סוכן הביטוח שלך וודא שגם השוכר עושה ביטוח התכולה שלו + צד ג' לדירה.",
    category: "כיסוי",
    triggerCondition: "policy_category = PROPERTY AND property_policy_count >= 2",
    triggerHint: "מספר פוליסות דירה",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: "שיפוץ הבית",
    body: "משפצים את הבית? הביטוח דירה כבר לא בתוקף. כדי לוודא שאתם מכוסים בתקופת השיפוץ, התייעצו עם סוכן הביטוח.",
    category: "כיסוי",
    triggerCondition: "policy_category = PROPERTY AND policy_subtype = דירה",
    triggerHint: "ביטוח דירה",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: "חשיפה למניות",
    body: "אנחנו אחרי שלוש שנים של עליות בבורסה. בדקו האם נכון להפחית או להגדיל את רמת החשיפה למניות. אולי לשנות מסלול.",
    category: "חיסכון",
    triggerCondition: "savings > 50000",
    triggerHint: "חיסכון/פנסיה",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: "רכיב מניות בפנסיה",
    body: "את הפנסיה תפגשו עוד עשרות שנים. שקלו להגדיל את רכיב המניות (אין בכך המלצה).",
    category: "חיסכון",
    triggerCondition: "age < 50 AND policy_category = PENSION",
    triggerHint: "גיל מתחת ל-50, יש פנסיה",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: "כסף בבנק",
    body: "תפסיקו לשחוק את הכסף שלכם בבנק. בשנים האחרונות מסלולים כלליים של חברות הביטוח הניבו בממוצע מעל 10% תשואה. לא חבל על הכסף שלכם?",
    category: "חיסכון",
    triggerCondition: "policy_count >= 2",
    triggerHint: "חיסכון קיים",
    source: "MANUAL",
    createdBy: "רפי",
  },
  {
    title: "תכנון פרישה",
    body: "הגעתם לגיל 60? זה הזמן להיפגש עם מתכנן פרישה כדי להגדיל את הפנסיה שלכם.",
    category: "שירות",
    triggerCondition: "age >= 60",
    triggerHint: "גיל 60+",
    source: "MANUAL",
    createdBy: "רפי",
  },
];

/**
 * The 18 hardcoded rules from all-rules.ts — converted to OfficeRule records.
 * These replace the code-level InsightRule objects.
 */
export const SYSTEM_RULES = [
  {
    title: "רכב חדש — בקש שמשות, פנסים ומראות מקוריים",
    body: "ברכבים חדשים מערכות הבטיחות תלויות בשמשות, פנסים ומראות מקוריים. חלפים תחליפיים עלולים לפגוע בפעולת המערכות.",
    category: "כיסוי",
    triggerCondition: "policy_category = PROPERTY AND vehicle_age <= 2",
    triggerHint: "רכב חדש עד גיל 2",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "חברות הביטוח מציעות מוצרי משכנתא",
    body: "משכנתא הפוכה, משכנתא ל-40 שנה, הלוואה לכל מטרה — כדאי לבדוק. חברות הביטוח נכנסו לעולם המשכנתאות עם מגוון מוצרים.",
    category: "כללי",
    triggerCondition: "age >= 30 AND age <= 65 AND policy_category = PROPERTY AND policy_subtype = דירה",
    triggerHint: "בעל נכס, גיל 30-65",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "לא בדקת ריבית משכנתא ב-5 שנים?",
    body: "אם לא בדקת את הריביות על המשכנתא שלך בחמש השנים האחרונות, יש סיכוי טוב שאפשר לחסוך.",
    category: "חיסכון",
    triggerCondition: "policy_subtype = משכנתא AND policy_age_years >= 5",
    triggerHint: "משכנתא פעילה מעל 5 שנים",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "אל תחכו עם ביטוח נסיעות לרגע האחרון",
    body: "רכישת ביטוח נסיעות לחו\"ל יחד עם כרטיסי הטיסה מספקת כיסויים רחבים יותר מאשר רכישה ברגע האחרון.",
    category: "כיסוי",
    triggerCondition: "policy_count >= 2 AND travel_season",
    triggerHint: "עונת טיסות, לקוח עם מספר פוליסות",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "ביטוח חיים — לא בדקת מחיר 3 שנים?",
    body: "מחירי השוק משתנים ויש סיכוי טוב לחיסכון בפרמיה של ביטוח חיים ותיק.",
    category: "חיסכון",
    triggerCondition: "policy_category = LIFE AND policy_age_years >= 3",
    triggerHint: "ביטוח חיים/סיכון מעל 3 שנים",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "ביטוח רפואי ישן — בדוק נספח תרופות",
    body: "נספחי תרופות מתעדכנים ויש טכנולוגיות חדשות שכדאי לוודא שהן מכוסות.",
    category: "כיסוי",
    triggerCondition: "policy_category = HEALTH AND policy_age_years >= 3",
    triggerHint: "ביטוח בריאות מעל 3 שנים",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "קרתה תאונה? רק מוסכי הסדר",
    body: "חברות הביטוח עשויות לקזז כ-30% מהתביעה אם לא נכנסת למוסך הסדר, באישור המפקח על הביטוח.",
    category: "שירות",
    triggerCondition: "policy_category = PROPERTY AND policy_subtype = רכב",
    triggerHint: "לקוח עם ביטוח רכב",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "יש לך דירה מושכרת?",
    body: "עדכן את סוכן הביטוח — וודא שגם השוכר עושה ביטוח תכולה + צד ג'.",
    category: "כיסוי",
    triggerCondition: "policy_category = PROPERTY AND property_policy_count >= 2",
    triggerHint: "מספר פוליסות רכוש",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "משפצים את הבית? הביטוח לא בתוקף",
    body: "בעת שיפוץ, ביטוח הדירה הרגיל עשוי שלא להיות בתוקף. כדי לוודא כיסוי בתקופת השיפוץ, חשוב להתייעץ עם סוכן הביטוח.",
    category: "כיסוי",
    triggerCondition: "policy_category = PROPERTY AND policy_subtype = דירה",
    triggerHint: "לקוח עם ביטוח דירה",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "בדקו את רמת החשיפה למניות",
    body: "אחרי שלוש שנים של עליות בבורסה, כדאי לבדוק האם נכון להפחית או להגדיל את רמת החשיפה למניות.",
    category: "חיסכון",
    triggerCondition: "savings > 50000",
    triggerHint: "חיסכון מצטבר מעל 50,000",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "הפנסיה עוד רחוקה — שקלו להגדיל מניות",
    body: "למי שעוד רחוק מגיל הפרישה, מסלול השקעה עם חשיפה גבוהה יותר למניות עשוי להניב תשואות טובות יותר לטווח ארוך. אין בכך המלצה.",
    category: "חיסכון",
    triggerCondition: "age < 50 AND policy_category = PENSION",
    triggerHint: "מתחת לגיל 50, יש פנסיה",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "תפסיקו לשחוק את הכסף שלכם בבנק",
    body: "בשנים האחרונות מסלולים כלליים של חברות הביטוח הניבו בממוצע מעל 10% תשואה שנתית. לא חבל על הכסף שיושב בפיקדון בנקאי?",
    category: "חיסכון",
    triggerCondition: "policy_count >= 2",
    triggerHint: "לקוח עם מספר פוליסות",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "הגעת לגיל 60 — זמן לתכנון פרישה",
    body: "בגיל 60 ומעלה, תכנון פרישה מקצועי יכול להגדיל משמעותית את הכנסת הפנסיה החודשית.",
    category: "שירות",
    triggerCondition: "age >= 60",
    triggerHint: "לקוח מעל גיל 60",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "לא נמצא ביטוח בריאות",
    body: "ביטוח בריאות פרטי מספק כיסוי חשוב שמשלים את סל הבריאות הציבורי — ניתוחים, תרופות, ייעוץ מומחים.",
    category: "כיסוי",
    triggerCondition: "no_policy_category = HEALTH AND policy_count >= 1",
    triggerHint: "לקוח ללא ביטוח בריאות",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "לקוח עם ענף ביטוח בודד",
    body: "לקוח שמרוכז בענף ביטוח אחד עשוי ליהנות מהרחבת הכיסוי לתחומים נוספים. זו הזדמנות לשיחה על צרכים נוספים.",
    category: "כללי",
    triggerCondition: "category_count = 1 AND policy_count >= 1",
    triggerHint: "ענף ביטוח בודד",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "דמי ניהול גבוהים מהצבירה",
    body: "בסכומים גבוהים, הפחתת דמי ניהול יכולה לחסוך אלפי שקלים בשנה.",
    category: "חיסכון",
    triggerCondition: "management_fee > 1.0 AND savings > 10000",
    triggerHint: "דמי ניהול מעל 1% וחיסכון מעל 10,000",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "פוליסה מתחדשת בקרוב",
    body: "זה הזמן לבדוק תנאי חידוש ולהשוות מחירים לפני שהפוליסה מתחדשת אוטומטית.",
    category: "חידוש",
    triggerCondition: "has_expiring_policy",
    triggerHint: "פוליסה שמסתיימת בתוך 90 יום",
    source: "SYSTEM",
    createdBy: "system",
  },
  {
    title: "לקוח רב-ענפי — הזדמנות לשיחה מקיפה",
    body: "לקוח שמופיע בשני הענפים (חיים ואלמנטרי) הוא לקוח מרכזי. שיחה מקיפה יכולה לחשוף פערים ולחזק את הקשר.",
    category: "כללי",
    triggerCondition: "has_life_and_elementary",
    triggerHint: "לקוח בענף חיים וגם אלמנטרי",
    source: "SYSTEM",
    createdBy: "system",
  },
];

export async function seedOfficeRules(): Promise<{ rafiCount: number; systemCount: number }> {
  const existing = await prisma.officeRule.count();
  if (existing > 0) {
    return { rafiCount: 0, systemCount: 0 };
  }

  const rafiResult = await prisma.officeRule.createMany({
    data: RAFI_RULES.map((r) => ({
      title: r.title,
      body: r.body,
      category: r.category,
      triggerCondition: r.triggerCondition,
      triggerHint: r.triggerHint,
      source: r.source,
      isActive: true,
      createdBy: r.createdBy,
    })),
  });

  const systemResult = await prisma.officeRule.createMany({
    data: SYSTEM_RULES.map((r) => ({
      title: r.title,
      body: r.body,
      category: r.category,
      triggerCondition: r.triggerCondition,
      triggerHint: r.triggerHint,
      source: r.source,
      isActive: true,
      createdBy: r.createdBy,
    })),
  });

  return { rafiCount: rafiResult.count, systemCount: systemResult.count };
}
